openapi: 3.0.2
info:
    title: Recommendation API
    version: 1.0.0
    description: Recommendation API for the Globex Retail site.
    license:
        name: MIT License
        url: 'https://opensource.org/licenses/MIT'
paths:
    '/score/{category}':
        description: ''
        get:
            parameters:
                -
                    examples:
                        product:
                            value: product
                    name: category
                    description: Identifier for the score category.
                    schema:
                        type: string
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/aggregated-score'
                            examples:
                                product:
                                    value:
                                        -
                                            productId: '329299'
                                            score: 148
                                        -
                                            productId: '329199'
                                            score: 145
                                        -
                                            productId: '165613'
                                            score: 141
                                        -
                                            productId: '165614'
                                            score: 138
                                        -
                                            productId: '165954'
                                            score: 132
                    description: Successful response. Returns an aggregated score.
                '404':
                    description: No data found for the given category.
                '500':
                    description: Internal Server Error.
            security:
                -
                    recommendation-api: []
            operationId: get-score
            summary: Get an aggregated score
            description: ''
        parameters:
            -
                name: category
                description: Identifier for the score category.
                schema:
                    type: string
                in: path
                required: true
components:
    schemas:
        aggregated-score:
            title: Root Type for aggregated-score
            description: ''
            type: array
            items:
                type: object
                properties:
                    productId:
                        type: string
                    score:
                        format: int32
                        type: integer
            example:
                -
                    productId: '329299'
                    score: 148
                -
                    productId: '329199'
                    score: 145
                -
                    productId: '165613'
                    score: 141
                -
                    productId: '165614'
                    score: 138
                -
                    productId: '165954'
                    score: 132
    securitySchemes:
        recommendation-api:
            type: apiKey
            name: api_key
            in: query
tags:
    -
        name: retail
        description: ''
    -
        name: recommendation
        description: ''
